"""Initial migration

Revision ID: 7f1963570ca8
Revises: 
Create Date: 2025-10-02 12:47:34.948905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1963570ca8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('opening_crawl', sa.String(), nullable=False),
    sa.Column('director', sa.String(), nullable=False),
    sa.Column('producer', sa.String(), nullable=False),
    sa.Column('release_date', sa.String(), nullable=False),
    sa.Column('created', sa.String(), nullable=True),
    sa.Column('edited', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rotation_period', sa.String(), nullable=False),
    sa.Column('orbital_period', sa.String(), nullable=False),
    sa.Column('diameter', sa.String(), nullable=False),
    sa.Column('climate', sa.String(), nullable=False),
    sa.Column('gravity', sa.String(), nullable=False),
    sa.Column('terrain', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('surface_water', sa.String(), nullable=False),
    sa.Column('population', sa.String(), nullable=False),
    sa.Column('created', sa.String(), nullable=True),
    sa.Column('edited', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('cost_in_credits', sa.String(), nullable=True),
    sa.Column('length', sa.String(), nullable=True),
    sa.Column('max_atmosphering_speed', sa.String(), nullable=True),
    sa.Column('crew', sa.String(), nullable=True),
    sa.Column('passengers', sa.String(), nullable=True),
    sa.Column('cargo_capacity', sa.String(), nullable=True),
    sa.Column('consumables', sa.String(), nullable=True),
    sa.Column('hyperdrive_rating', sa.String(), nullable=True),
    sa.Column('MGLT', sa.String(), nullable=True),
    sa.Column('starship_class', sa.String(), nullable=True),
    sa.Column('created', sa.String(), nullable=True),
    sa.Column('edited', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('cost_in_credits', sa.String(), nullable=True),
    sa.Column('length', sa.String(), nullable=True),
    sa.Column('max_atmosphering_speed', sa.String(), nullable=True),
    sa.Column('crew', sa.String(), nullable=True),
    sa.Column('passengers', sa.String(), nullable=True),
    sa.Column('cargo_capacity', sa.String(), nullable=True),
    sa.Column('consumables', sa.String(), nullable=True),
    sa.Column('vehicle_class', sa.String(), nullable=True),
    sa.Column('created', sa.String(), nullable=True),
    sa.Column('edited', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('films_planets',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], )
    )
    op.create_table('films_starships',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('starship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.id'], )
    )
    op.create_table('films_vehicles',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], )
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('height', sa.String(), nullable=False),
    sa.Column('mass', sa.String(), nullable=False),
    sa.Column('hair_color', sa.String(), nullable=False),
    sa.Column('skin_color', sa.String(), nullable=False),
    sa.Column('eye_color', sa.String(), nullable=False),
    sa.Column('birth_year', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('homeworld_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.String(), nullable=True),
    sa.Column('edited', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['homeworld_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('average_height', sa.String(), nullable=False),
    sa.Column('skin_colors', sa.String(), nullable=False),
    sa.Column('hair_colors', sa.String(), nullable=False),
    sa.Column('eye_colors', sa.String(), nullable=False),
    sa.Column('average_lifespan', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('homeworld_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.String(), nullable=True),
    sa.Column('edited', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['homeworld_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('films_people',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], )
    )
    op.create_table('films_species',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], )
    )
    op.create_table('people_starships',
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('starship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.id'], )
    )
    op.create_table('people_vehicles',
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], )
    )
    op.create_table('species_people',
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species_people')
    op.drop_table('people_vehicles')
    op.drop_table('people_starships')
    op.drop_table('films_species')
    op.drop_table('films_people')
    op.drop_table('species')
    op.drop_table('people')
    op.drop_table('films_vehicles')
    op.drop_table('films_starships')
    op.drop_table('films_planets')
    op.drop_table('vehicles')
    op.drop_table('starships')
    op.drop_table('planets')
    op.drop_table('films')
    # ### end Alembic commands ###
